package com.gitb.vs.tdl.rules;

public enum TestCaseSection {

    START,
    METADATA,
    NAMESPACES,
    IMPORTS,
    PRELIMINARY,
    VARIABLES,
    ACTORS,
    STEPS,
    SCRIPTLETS,
    SCRIPTLET_START,
    SCRIPTLET_METADATA,
    SCRIPTLET_NAMESPACES,
    SCRIPTLET_IMPORTS,
    SCRIPTLET_PARAMETERS,
    SCRIPTLET_VARIABLES,
    SCRIPTLET_STEPS,
    SCRIPTLET_OUTPUT,
    SCRIPTLET_END,
    END

}
