apiVersion: apps/v1
kind: Deployment
metadata:
  name: "itb-srv"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: itb-srv
  template:
    metadata:
      labels:
        app.kubernetes.io/name: itb-srv
    spec:
      automountServiceAccountToken: false
      containers:
        - image: "isaitb/gitb-srv:1.24.4"
          imagePullPolicy: "IfNotPresent"
          name: itb-srv
          env:
            - name: remote.testcase.repository.url
              value: "http://itb-ui:9000/itb/api/repository/tests/:test_id/definition"
            - name: remote.testresource.repository.url
              value: "http://itb-ui:9000/itb/api/repository/resource/:test_id/:resource_id"
            - name: CALLBACK_ROOT_URL
              value: "https://localhost/itbsrv"
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: "Always"
