apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: itb-ingress
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - localhost
      secretName: itb-tls-secret
  rules:
    - host: localhost
      http:
        paths:
          - path: /itbsrv
            pathType: Prefix
            backend:
              service:
                name: itb-srv
                port:
                  number: 8080
          - path: /itb
            pathType: Prefix
            backend:
              service:
                name: itb-ui
                port:
                  number: 9000