apiVersion: v2
name: itb
version: 1.7.0
description: A Helm chart to install the Interoperability Test Bed (ITB) on Kubernetes
type: application
keywords:
  - itb
  - gitb
  - interoperability
  - conformance
  - test
home: https://interoperable-europe.ec.europa.eu/collection/interoperability-test-bed-repository/solution/interoperability-test-bed
sources:
  - https://github.com/ISAITB/gitb
maintainers:
  - name: Interoperability Test Bed Team (European Commission, DIGIT)
    email: DIGIT-ITB@ec.europa.eu
    url: https://ec.europa.eu/info/departments/informatics_en
icon: https://www.itb.ec.europa.eu/files/itb_logo.png
appVersion: "1.27.2"