
package com.gitb.engine.messaging.handlers.layer.application.domibus.stub.ecodex;

import jakarta.xml.ws.*;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "BackendService_1_1", targetNamespace = "http://org.ecodex.backend/1_1/", wsdlLocation = "http://org.ecodex.backend/1_1/")
public class BackendService11
    extends Service
{

    private static final URL BACKENDSERVICE11_WSDL_LOCATION;
    private static final WebServiceException BACKENDSERVICE11_EXCEPTION;
    private static final QName BACKENDSERVICE11_QNAME = new QName("http://org.ecodex.backend/1_1/", "BackendService_1_1");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://org.ecodex.backend/1_1/");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BACKENDSERVICE11_WSDL_LOCATION = url;
        BACKENDSERVICE11_EXCEPTION = e;
    }

    public BackendService11() {
        super(__getWsdlLocation(), BACKENDSERVICE11_QNAME);
    }

    public BackendService11(WebServiceFeature... features) {
        super(__getWsdlLocation(), BACKENDSERVICE11_QNAME, features);
    }

    public BackendService11(URL wsdlLocation) {
        super(wsdlLocation, BACKENDSERVICE11_QNAME);
    }

    public BackendService11(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BACKENDSERVICE11_QNAME, features);
    }

    public BackendService11(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BackendService11(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BackendInterface
     */
    @WebEndpoint(name = "BACKEND_PORT")
    public BackendInterface getBACKENDPORT() {
        return super.getPort(new QName("http://org.ecodex.backend/1_1/", "BACKEND_PORT"), BackendInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BackendInterface
     */
    @WebEndpoint(name = "BACKEND_PORT")
    public BackendInterface getBACKENDPORT(WebServiceFeature... features) {
        return super.getPort(new QName("http://org.ecodex.backend/1_1/", "BACKEND_PORT"), BackendInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BACKENDSERVICE11_EXCEPTION!= null) {
            throw BACKENDSERVICE11_EXCEPTION;
        }
        return BACKENDSERVICE11_WSDL_LOCATION;
    }

}
