
package com.gitb.engine.messaging.handlers.layer.application.domibus.stub.ecodex;

import com.gitb.engine.messaging.handlers.layer.application.domibus.stub.ebms.Messaging;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Holder;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BackendInterface", targetNamespace = "http://org.ecodex.backend/1_1/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        com.gitb.engine.messaging.handlers.layer.application.domibus.stub.ecodex.ObjectFactory.class,
        com.gitb.engine.messaging.handlers.layer.application.domibus.stub.ebms.ObjectFactory.class,
        com.gitb.engine.messaging.handlers.layer.application.domibus.stub.xmlmime.ObjectFactory.class
})
public interface BackendInterface {


    /**
     * 
     * @param listPendingMessagesRequest
     * @return
     *     returns backend.ecodex.org._1_1.ListPendingMessagesResponse
     */
    @WebMethod
    @WebResult(name = "listPendingMessagesResponse", targetNamespace = "http://org.ecodex.backend/1_1/", partName = "listPendingMessagesResponse")
    public ListPendingMessagesResponse listPendingMessages(
        @WebParam(name = "listPendingMessagesRequest", targetNamespace = "http://org.ecodex.backend/1_1/", partName = "listPendingMessagesRequest")
        Object listPendingMessagesRequest);

    /**
     * 
     * @param getErrorsRequest
     * @return
     *     returns backend.ecodex.org._1_1.ErrorResultImplArray
     */
    @WebMethod
    @WebResult(name = "getMessageErrorsResponse", targetNamespace = "http://org.ecodex.backend/1_1/", partName = "getMessageErrorsResponse")
    public ErrorResultImplArray getMessageErrors(
        @WebParam(name = "getErrorsRequest", targetNamespace = "http://org.ecodex.backend/1_1/", partName = "getErrorsRequest")
        GetErrorsRequest getErrorsRequest);

    /**
     * 
     * @param statusRequest
     * @return
     *     returns backend.ecodex.org._1_1.MessageStatus
     * @throws StatusFault
     */
    @WebMethod
    @WebResult(name = "getStatusResponse", targetNamespace = "http://org.ecodex.backend/1_1/", partName = "getStatusResponse")
    public MessageStatus getStatus(
        @WebParam(name = "statusRequest", targetNamespace = "http://org.ecodex.backend/1_1/", partName = "statusRequest")
        StatusRequest statusRequest)
        throws StatusFault
    ;

    /**
     * 
     * @param ebMSHeaderInfo
     * @param submitRequest
     * @return
     *     returns backend.ecodex.org._1_1.SubmitResponse
     * @throws SubmitMessageFault
     */
    @WebMethod
    @WebResult(name = "submitResponse", targetNamespace = "http://org.ecodex.backend/1_1/", partName = "submitResponse")
    public SubmitResponse submitMessage(
        @WebParam(name = "submitRequest", targetNamespace = "http://org.ecodex.backend/1_1/", partName = "submitRequest")
        SubmitRequest submitRequest,
        @WebParam(name = "Messaging", targetNamespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/", header = true, partName = "ebMSHeaderInfo")
        Messaging ebMSHeaderInfo)
        throws SubmitMessageFault
    ;

    /**
     * 
     * @param ebMSHeaderInfo
     * @param retrieveMessageRequest
     * @param retrieveMessageResponse
     * @throws RetrieveMessageFault
     */
    @WebMethod
    public void retrieveMessage(
        @WebParam(name = "retrieveMessageRequest", targetNamespace = "http://org.ecodex.backend/1_1/", partName = "retrieveMessageRequest")
        RetrieveMessageRequest retrieveMessageRequest,
        @WebParam(name = "retrieveMessageResponse", targetNamespace = "http://org.ecodex.backend/1_1/", mode = WebParam.Mode.OUT, partName = "retrieveMessageResponse")
        Holder<RetrieveMessageResponse> retrieveMessageResponse,
        @WebParam(name = "Messaging", targetNamespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/", header = true, mode = WebParam.Mode.OUT, partName = "ebMSHeaderInfo")
        Holder<Messaging> ebMSHeaderInfo)
        throws RetrieveMessageFault
    ;

}
