apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dbVolumeName" . | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.database.storage | default "100Mi" | quote }}
