apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  {{- if .Values.ingress.annotations }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.class }}
  ingressClassName: {{ .Values.ingress.class }}
  {{- end }}
  {{- if and .Values.ingress.tls .Values.ingress.tls.host .Values.ingress.tls.secretName }}
  tls:
    - hosts:
        - {{ .Values.ingress.tls.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ include "ingress.host" . | quote }}
      http:
        paths:
          - path: {{ include "ingress.srvPath" . | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "srv.serviceName" . }}
                port:
                  number: {{ include "srv.servicePort" . }}
          - path: {{ include "ingress.uiPath" . | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "ui.serviceName" . }}
                port:
                  number: {{ include "ui.servicePort" . }}