apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.serviceName" . | quote }}
spec:
  type: {{ .Values.redis.serviceType | default "ClusterIP" | quote }}
  ports:
    - name: {{ include "redis.servicePort" . | quote }}
      port: {{ include "redis.servicePort" . }}
      targetPort: {{ include "redis.port" . }}
  selector:
    app.kubernetes.io/name: {{ include "redis.name" . }}
