apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "repoVolumeName" . | quote }}
  {{- if .Values.volume.repository.annotations }}
  annotations:
  {{- range $key, $value := .Values.volume.repository.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.repository.storage | default "100Mi" | quote }}
