apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "repoVolumeName" . | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.repository.storage | default "100Mi" | quote }}
