apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "srv.name" . | quote }}
spec:
  replicas: {{ .Values.srv.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "srv.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "srv.name" . }}
    spec:
      automountServiceAccountToken: false
      containers:
        - image: {{ .Values.srv.image | quote }}
          imagePullPolicy: {{ .Values.srv.imagePullPolicy | default "IfNotPresent" | quote }}
          name: {{ include "srv.name" . }}
          env:
          {{- if or (not .Values.srv.env) (not (index .Values.srv.env "server.servlet.context-path")) }}
            - name: server.servlet.context-path
              value: {{ include "srv.contextRoot" . | quote }}
          {{- end }}
          {{- if or (not .Values.srv.env) (not .Values.srv.env.CALLBACK_ROOT_URL) }}
            - name: CALLBACK_ROOT_URL
              value: {{ include "srv.callbackRoot" . | quote }}
          {{- end }}
          {{- if or (not .Values.srv.env) (not .Values.srv.env.REPOSITORY_ROOT_URL) }}
            - name: REPOSITORY_ROOT_URL
              value: "http://{{ include "ui.serviceName" . }}:{{ include "ui.servicePort" . }}{{ include "ui.contextRoot" . }}"
          {{- end }}
          {{- if .Values.srv.env }}
          {{- range $key, $value := .Values.srv.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          ports:
            - containerPort: {{ include "srv.port" . }}
              protocol: TCP
      restartPolicy: {{ .Values.srv.restartPolicy | default "Always" | quote }}
