apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ui.name" . | quote }}
spec:
  replicas: {{ .Values.ui.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ui.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ui.name" . }}
    spec:
      automountServiceAccountToken: false
      containers:
        - image: {{ .Values.ui.image | quote }}
          imagePullPolicy: {{ .Values.ui.imagePullPolicy | default "IfNotPresent" | quote }}
          name: {{ include "ui.name" . }}
          env:
            - name: TESTBED_SERVICE_URL
              value: "http://{{ include "srv.serviceName" . }}:{{ include "srv.servicePort" . }}{{ include "srv.contextRoot" . }}/TestbedService"
            - name: TESTBED_CLIENT_URL_INTERNAL
              value: "http://0.0.0.0:{{ include "ui.callbackPort" . }}{{ include "ui.contextRoot" . }}/TestbedClient"
            - name: TESTBED_CLIENT_URL
              value: "http://{{ include "ui.serviceName" . }}:{{ include "ui.serviceCallbackPort" . }}{{ include "ui.contextRoot" . }}/TestbedClient"
          {{- if or (not .Values.ui.env) (not .Values.ui.env.DB_DEFAULT_URL) }}
            - name: DB_DEFAULT_URL
              value: "jdbc:mysql://{{ include "mysql.serviceName" . }}:{{ include "mysql.servicePort" . }}/{{ include "mysql.dbName" . }}?characterEncoding=UTF-8&useUnicode=true&autoReconnect=true&useSSL=false&verifyServerCertificate=false&allowPublicKeyRetrieval=true"
          {{- end }}
            - name: DB_DEFAULT_ROOTURL
              value: "jdbc:mysql://{{ include "mysql.serviceName" . }}:{{ include "mysql.servicePort" . }}/"
          {{- if or (not .Values.ui.env) (not .Values.ui.env.DB_DEFAULT_NAME) }}
            - name: DB_DEFAULT_NAME
              value: {{ include "mysql.dbName" . | quote }}
          {{- end }}
            - name: REDIS_HOST
              value: {{ include "redis.serviceName" . | quote }}
          {{- if or (not .Values.ui.env) (not .Values.ui.env.WEB_CONTEXT_ROOT) }}
            - name: WEB_CONTEXT_ROOT
              value: {{ include "ui.contextRoot" . | quote }}
          {{- end }}
          {{- if or (not .Values.ui.env) (not .Values.ui.env.AUTHENTICATION_COOKIE_PATH) }}
            - name: AUTHENTICATION_COOKIE_PATH
              value: {{ include "ui.authenticationCookiePath" . | quote }}
          {{- end }}
          {{- if or (not .Values.ui.env) (not .Values.ui.env.TESTBED_HOME_LINK) }}
            - name: TESTBED_HOME_LINK
              value: {{ include "ui.homeLink" . | quote }}
          {{- end }}
          {{- if .Values.ui.env }}
          {{- range $key, $value := .Values.ui.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          ports:
            - containerPort: {{ include "ui.port" . }}
              protocol: TCP
            - containerPort: {{ include "ui.callbackPort" . }}
              protocol: TCP
          volumeMounts:
            - mountPath: {{ .Values.ui.repositoryPath | default "/gitb-repository" | quote }}
              name: {{ include "repoVolumeName" . }}
      restartPolicy: {{ .Values.ui.restartPolicy | default "Always" | quote }}
      volumes:
        - name: {{ include "repoVolumeName" . }}
          persistentVolumeClaim:
            claimName: {{ include "repoVolumeName" . }}
