/*
 * Copyright (C) 2026 European Union
 *
 * Licensed under the EUPL, Version 1.2 or - as soon they will be approved by the European Commission - subsequent
 * versions of the EUPL (the "Licence"); You may not use this work except in compliance with the Licence.
 *
 * You may obtain a copy of the Licence at:
 *
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the Licence is distributed on an
 * "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the Licence for
 * the specific language governing permissions and limitations under the Licence.
 */

package com.gitb.engine.validation.handlers.schematron;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NamedNodeMap;
import org.w3c.dom.Node;

import javax.xml.XMLConstants;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Resolves the node referred to by a Schematron SVRL {@code @location} XPath expression, without needing a full
 * XPath evaluation for the vast majority of cases.
 * <p/>
 * The ISO Schematron skeleton (as bundled by ph-schematron, used to compile {@code .sch} rules and used as-is for
 * pre-compiled {@code .xslt} rules) always generates {@code @location} values in one fixed, canonical syntax (the
 * "ugly though full XPath for locators" produced by its {@code schematron-select-full-path} mode, notation "1"):
 * a sequence of absolute, positional steps of the form {@code /*:local[namespace-uri()='uri'][n]} (or
 * {@code /local[n]} for elements with no namespace, and a trailing {@code @*[local-name()='name' and
 * namespace-uri()='uri']} or {@code @name} for attributes).
 * <p/>
 * Evaluating that expression via a general-purpose XPath engine against the line-numbered DOM is expensive for large documents: that
 * DOM is deliberately non-namespace-aware (elements are created with {@code doc.createElement(qName)}), so Saxon's
 * DOM adapter has to reconstruct each node's namespace by walking its ancestor chain, and to hold a document-wide
 * lock for every attribute access. With one XPath evaluation per report item this cost is paid repeatedly - often
 * thousands of times for a large, heavily-annotated document.
 * <p/>
 * This resolver instead recognises the canonical path syntax directly and walks the DOM tree itself
 * ({@code getFirstChild()}/{@code getNextSibling()}), carrying forward the in-scope namespace prefixes as it
 * descends (computed from the {@code xmlns}/{@code xmlns:*} attributes actually present on the line-numbered DOM,
 * since those survive as ordinary attributes on that non-namespace-aware tree). Resolved path prefixes are
 * memoised, so report items that share an ancestor (the common case) skip the sibling scan for that ancestor.
 * <p/>
 * Whenever the expression is not in the canonical form, or does not resolve to an actual node, {@link #resolve}
 * returns an empty result and the caller is expected to fall back to a full XPath evaluation. This keeps the
 * resolver a pure optimisation: it can never produce a different answer than that fallback, only skip the cost of
 * getting there.
 */
class SchematronLocationResolver {

    // The position group is bounded (rather than unbounded "\d+") so a malformed/adversarial expression cannot make
    // Integer.parseInt(...) throw on an implausibly long digit run.
    private static final Pattern ELEMENT_WITH_NAMESPACE = Pattern.compile("^\\*:([A-Za-z_][\\w.\\-]*)\\[namespace-uri\\(\\)='([^']*)'\\]\\[(\\d{1,9})]$");
    private static final Pattern ELEMENT_WITHOUT_NAMESPACE = Pattern.compile("^([A-Za-z_][\\w.\\-]*)\\[(\\d{1,9})]$");
    private static final Pattern ATTRIBUTE_WITH_NAMESPACE = Pattern.compile("^@\\*\\[local-name\\(\\)='([^']*)' and namespace-uri\\(\\)='([^']*)']$");
    private static final Pattern ATTRIBUTE_WITHOUT_NAMESPACE = Pattern.compile("^@([A-Za-z_][\\w.\\-]*)$");

    private final Document document;
    private final Map<String, MatchResult> cache = new HashMap<>();

    /**
     * Constructor.
     *
     * @param document The line-numbered document to resolve locations against.
     */
    SchematronLocationResolver(Document document) {
        this.document = document;
    }

    /**
     * Resolve the node referred to by the provided canonical location XPath expression.
     *
     * @param canonicalXPathExpression The expression (as generated by the ISO Schematron skeleton).
     * @return The located node, or empty if the expression is not in the recognised canonical form, or does not
     * resolve to a node.
     */
    Optional<Node> resolve(String canonicalXPathExpression) {
        List<String> rawSteps = splitSteps(canonicalXPathExpression);
        if (rawSteps == null) {
            return Optional.empty();
        }
        List<Step> steps = new ArrayList<>(rawSteps.size());
        for (String rawStep: rawSteps) {
            Step step = parseStep(rawStep);
            if (step == null) {
                return Optional.empty();
            }
            steps.add(step);
        }
        StringBuilder pathBuilder = new StringBuilder();
        Node currentNode = document;
        Map<String, String> currentScope = Map.of();
        for (int i = 0; i < steps.size(); i++) {
            Step step = steps.get(i);
            pathBuilder.append('/').append(rawSteps.get(i));
            String cacheKey = pathBuilder.toString();
            MatchResult cached = cache.get(cacheKey);
            if (cached != null) {
                currentNode = cached.node();
                currentScope = cached.scope();
                continue;
            }
            MatchResult result;
            if (step.attribute()) {
                if (!(currentNode instanceof Element element)) {
                    return Optional.empty();
                }
                Node attribute = findAttribute(element, step, currentScope);
                if (attribute == null) {
                    return Optional.empty();
                }
                result = new MatchResult(attribute, currentScope);
            } else if (i == 0) {
                if (!(currentNode instanceof Document doc) || doc.getDocumentElement() == null) {
                    return Optional.empty();
                }
                Element docElement = doc.getDocumentElement();
                Map<String, String> rootScope = mergeNamespaces(currentScope, docElement);
                if (step.position() != 1 || !localNameAndNamespaceMatch(docElement, step, rootScope)) {
                    return Optional.empty();
                }
                result = new MatchResult(docElement, rootScope);
            } else {
                if (!(currentNode instanceof Element parentElement)) {
                    return Optional.empty();
                }
                result = findChildElement(parentElement, step, currentScope);
                if (result == null) {
                    return Optional.empty();
                }
            }
            cache.put(cacheKey, result);
            currentNode = result.node();
            currentScope = result.scope();
        }
        return Optional.of(currentNode);
    }

    /**
     * Split an absolute canonical location expression into its individual steps.
     * <p/>
     * A plain {@code split('/')} is not safe here since a namespace URI predicate can itself contain slashes
     * (most real-world namespace URIs are HTTP(S) URLs). Splitting is instead only done on a {@code /} found
     * outside of a {@code [...]} predicate.
     *
     * @param expression The expression to split.
     * @return The individual (still raw) steps, or {@code null} if the expression is not an absolute path.
     */
    private static List<String> splitSteps(String expression) {
        if (expression == null || expression.isEmpty() || expression.charAt(0) != '/') {
            return null;
        }
        List<String> steps = new ArrayList<>();
        int depth = 0;
        int start = 1;
        for (int i = 1; i < expression.length(); i++) {
            char c = expression.charAt(i);
            if (c == '[') {
                depth++;
            } else if (c == ']') {
                depth--;
            } else if (c == '/' && depth == 0) {
                steps.add(expression.substring(start, i));
                start = i + 1;
            }
        }
        steps.add(expression.substring(start));
        for (String step: steps) {
            if (step.isEmpty()) {
                return null;
            }
        }
        return steps;
    }

    /**
     * Parse a single raw step into its structured form.
     *
     * @param rawStep The raw step text (without the leading {@code /}).
     * @return The parsed step, or {@code null} if the step is not in one of the recognised canonical forms.
     */
    private static Step parseStep(String rawStep) {
        Matcher matcher = ELEMENT_WITH_NAMESPACE.matcher(rawStep);
        if (matcher.matches()) {
            return new Step(false, matcher.group(1), matcher.group(2), Integer.parseInt(matcher.group(3)));
        }
        matcher = ATTRIBUTE_WITH_NAMESPACE.matcher(rawStep);
        if (matcher.matches()) {
            return new Step(true, matcher.group(1), matcher.group(2), 0);
        }
        matcher = ATTRIBUTE_WITHOUT_NAMESPACE.matcher(rawStep);
        if (matcher.matches()) {
            return new Step(true, matcher.group(1), "", 0);
        }
        matcher = ELEMENT_WITHOUT_NAMESPACE.matcher(rawStep);
        if (matcher.matches()) {
            return new Step(false, matcher.group(1), "", Integer.parseInt(matcher.group(2)));
        }
        return null;
    }

    /**
     * Find the n-th (per the step's position) child element of the provided parent matching the step's local name
     * and namespace.
     *
     * @param parent The parent element to search under.
     * @param step The step to match.
     * @param parentScope The namespace prefixes in scope for the parent element.
     * @return The matched element together with its own namespace scope, or {@code null} if not found.
     */
    private static MatchResult findChildElement(Element parent, Step step, Map<String, String> parentScope) {
        int matchCount = 0;
        for (Node child = parent.getFirstChild(); child != null; child = child.getNextSibling()) {
            if (child.getNodeType() != Node.ELEMENT_NODE) {
                continue;
            }
            Element candidate = (Element) child;
            Map<String, String> scope = mergeNamespaces(parentScope, candidate);
            if (!localNameAndNamespaceMatch(candidate, step, scope)) {
                continue;
            }
            matchCount++;
            if (matchCount == step.position()) {
                return new MatchResult(candidate, scope);
            }
        }
        return null;
    }

    /**
     * Find the attribute of the provided element matching the step's local name and namespace.
     *
     * @param element The element whose attributes to search.
     * @param step The step to match.
     * @param scope The namespace prefixes in scope for the element.
     * @return The matched attribute node, or {@code null} if not found.
     */
    private static Node findAttribute(Element element, Step step, Map<String, String> scope) {
        NamedNodeMap attributes = element.getAttributes();
        if (attributes == null) {
            return null;
        }
        for (int i = 0; i < attributes.getLength(); i++) {
            Node attribute = attributes.item(i);
            String name = attribute.getNodeName();
            if (isNamespaceDeclaration(name)) {
                continue;
            }
            int colonIndex = name.indexOf(':');
            String localName = colonIndex < 0 ? name : name.substring(colonIndex + 1);
            if (!localName.equals(step.localName())) {
                continue;
            }
            // Unlike elements, an unprefixed attribute is never affected by a default namespace declaration.
            String uri = colonIndex < 0 ? "" : scope.get(name.substring(0, colonIndex));
            if (uri != null && uri.equals(step.namespaceUri())) {
                return attribute;
            }
        }
        return null;
    }

    /**
     * Check whether the provided candidate element's local name and (resolved) namespace match the step.
     *
     * @param candidate The candidate element.
     * @param step The step to match.
     * @param scope The namespace prefixes in scope for the candidate (including its own declarations).
     * @return The check's outcome.
     */
    private static boolean localNameAndNamespaceMatch(Element candidate, Step step, Map<String, String> scope) {
        String qName = candidate.getNodeName();
        int colonIndex = qName.indexOf(':');
        String localName = colonIndex < 0 ? qName : qName.substring(colonIndex + 1);
        if (!localName.equals(step.localName())) {
            return false;
        }
        String prefix = colonIndex < 0 ? "" : qName.substring(0, colonIndex);
        String uri = scope.get(prefix);
        if (uri == null) {
            // An unprefixed element with no default namespace declared in scope has no namespace. A prefixed
            // element whose prefix is not in scope is not well-formed XML - treat it as a non-match rather than
            // guessing, the caller falls back to a full XPath evaluation in that case.
            uri = colonIndex < 0 ? "" : null;
        }
        return step.namespaceUri().equals(uri);
    }

    /**
     * Merge the namespace declarations carried by the provided element's own {@code xmlns}/{@code xmlns:*}
     * attributes into the parent scope, to get the namespace scope in effect for (and within) that element.
     * <p/>
     * The parent scope map is returned unchanged (no copy) if the element declares no namespaces of its own, which
     * is the common case.
     *
     * @param parentScope The namespace scope in effect for the element's parent.
     * @param element The element to examine.
     * @return The namespace scope (prefix, using the empty string for the default namespace, to URI).
     */
    private static Map<String, String> mergeNamespaces(Map<String, String> parentScope, Element element) {
        NamedNodeMap attributes = element.getAttributes();
        Map<String, String> scope = parentScope;
        for (int i = 0; i < attributes.getLength(); i++) {
            Node attribute = attributes.item(i);
            String name = attribute.getNodeName();
            String prefix;
            if (name.equals(XMLConstants.XMLNS_ATTRIBUTE)) {
                prefix = "";
            } else if (name.startsWith(XMLConstants.XMLNS_ATTRIBUTE + ":")) {
                prefix = name.substring(XMLConstants.XMLNS_ATTRIBUTE.length() + 1);
            } else {
                continue;
            }
            if (scope == parentScope) {
                scope = new HashMap<>(parentScope);
            }
            scope.put(prefix, attribute.getNodeValue());
        }
        return scope;
    }

    /**
     * Check whether the provided attribute name is a namespace declaration ({@code xmlns} or {@code xmlns:*}).
     *
     * @param name The attribute name.
     * @return The check's outcome.
     */
    private static boolean isNamespaceDeclaration(String name) {
        return name.equals(XMLConstants.XMLNS_ATTRIBUTE) || name.startsWith(XMLConstants.XMLNS_ATTRIBUTE + ":");
    }

    /**
     * A single, parsed step of a canonical location expression.
     *
     * @param attribute Whether this is a trailing attribute step.
     * @param localName The local name to match.
     * @param namespaceUri The namespace URI to match (empty string for "no namespace").
     * @param position The 1-based position among same-name, same-namespace siblings (unused for attribute steps).
     */
    private record Step(boolean attribute, String localName, String namespaceUri, int position) {}

    /**
     * The result of successfully matching a single step: the matched node together with the namespace scope in
     * effect for it (needed to resolve the next step, if any).
     *
     * @param node The matched node.
     * @param scope The namespace scope in effect for the node.
     */
    private record MatchResult(Node node, Map<String, String> scope) {}

}
