name: quality
on:
  push:
    branches:
      - "*"
  workflow_dispatch:
jobs:
  build:
    name: Quality build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Install SBT
        uses: sbt/setup-sbt@v1
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-${{ secrets.CACHE_VERSION }}
      - name: Generate Maven settings
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: >
            [
              {
                "id": "itbRepoRead",
                "name": "itbRepoRead",
                "url": "${{ secrets.ITB_MVN_REPO_URL }}",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true"
                }
              }
            ]
          servers: >
            [
              {
                "id": "itbRepoRead",
                "username": "${{ secrets.ITB_MVN_REPO_USER }}",
                "password": "${{ secrets.ITB_MVN_REPO_PASS }}"
              }
            ]
          profiles: >
            [
              {
                "id": "itbRepoRead",
                "properties": {
                  "itbRepoReadUrl": "${{ secrets.ITB_MVN_REPO_URL }}"
                }
              }
            ]
          active_profiles: >
            [
              "itbRepoRead", "github"
            ]
      - name: Build gitb-srv
        run: mvn -B install --file pom.xml -DskipTests=true
      - name: Build gitb-ui
        run: |
          cd gitb-ui
          sbt clean dist
      - name: Run quality analysis
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=isaitb
            -Dsonar.projectKey=ISAITB_gitb
            -Dsonar.sources=.
            -Dsonar.inclusions=**/*.java,**/*.scala,**/*.ts,**/*.js
            -Dsonar.exclusions=**/test/**,**/src/test/**,**/node_modules/**,**/dist/**,**/target/generated-sources/**
            -Dsonar.java.binaries=gitb-common/target/classes,gitb-core/target/classes,gitb-engine/target/classes,gitb-lib/target/classes,gitb-reports/target/classes,gitb-testbed-service/target/classes,gitb-validator-tdl/target/classes
            -Dsonar.scala.version=2.13
            -Dsonar.scala.binaries=gitb-ui/target/scala-*/classes
            -Dsonar.javascript.tsconfigPath=gitb-ui/ui/tsconfig.json
